from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent
from langchain_core.messages.ai import AIMessage

from app.config.setting import Settings
from app.common import logger, CustomExceptions

logger = logger.get_logger(__name__)
c_exception = CustomExceptions.CustomException

def get_response_from_ai_agents(llm_id, query, allow_search, system_prompt):
    try:
        llm = ChatGroq(model=llm_id)
        tools = [TavilySearchResults(max_results=1)] if allow_search else []
        agent = create_react_agent(model=llm, tools=tools)
        state = {
            "messages": [system_prompt] + query
        }
        response = agent.invoke(state)
        messages = response.get("messages", [])
        ai_messages = [msg.content for msg in messages if isinstance(msg, AIMessage)]

        if not ai_messages:
            return "No response generated by AI agents."

        return ai_messages[-1]

    except Exception as e:
        error_message = c_exception("Unable to generate response", e)
        logger.error(str(error_message))
        raise